### PR TITLE
Add missing go:embed directive for sysproxy binary

### PR DESCRIPTION
**Pull request by atavism**
Resolves https://github.com/getlantern/lantern-binaries/issues/9

### CODE REVIEW

**Comment by atavism** [comment]
I confirmed I'm able to run Lantern on Ubuntu 22.10 with these changes. Lantern successfully sets itself as system proxy:

image

**Review by soltzen — APPROVED** [review]
LGTM

**Comment by atavism** [comment]
Thanks for the review, @soltzen!

**Review by myleshorton — APPROVED** [review]

**Review by myleshorton — APPROVED** [review]

**Comment by myleshorton** [comment]
LGTM! Let's go ahead and merge, as this is unrelated to the libayatana issues mentioned here https://github.com/getlantern/lantern-desktop/pull/323

**Comment by atavism** [comment]
Thanks, @myleshorton!

**Pull request merged**
